eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://summerli:123@euk1.com:7901/eureka/
  instance:
    hostname: euk1.com
  #关闭eureka的自我保护功能
  server:
    enable-self-preservation: true

server:
  port: 7901
spring:
  application:
    name: EurekaServer
  security:
    user:
      name: summerli
      password: 123
  boot:
    admin:
      client:
        url: http://localhost:8080
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
